package com.plcoding.tracker_data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a tracked food item in the local database.
 *
 * @property name The name of the food.
 * @property carbs The amount of carbohydrates in grams.
 * @property protein The amount of protein in grams.
 * @property fat The amount of fat in grams.
 * @property imageUrl The URL of an image of the food, if available.
 * @property type The type of meal (e.g., "breakfast", "lunch").
 * @property amount The amount of the food in grams.
 * @property dayOfMonth The day of the month the food was tracked.
 * @property month The month the food was tracked.
 * @property year The year the food was tracked.
 * @property calories The number of calories.
 * @property id The unique identifier for the entity. It is auto-generated by Room.
 */
@Entity
data class TrackedFoodEntity(
    val name: String,
    val carbs: Int,
    val protein: Int,
    val fat: Int,
    val imageUrl: String?,
    val type: String,
    val amount: Int,
    val dayOfMonth: Int,
    val month: Int,
    val year: Int,
    val calories: Int,
    @PrimaryKey val id: Int? = null
)
